version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=e_learning_platform.settings
      - PYTHONUNBUFFERED=1
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
